In [1]:
# import libraries
# !pip install kaggle

import kaggle

In [2]:
# download the dataset using kaggle api
!kaggle datasets download -d ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [3]:
# extract the file from zip file 

import zipfile

zip_file = zipfile.ZipFile('orders.csv.zip')
zip_file.extractall() # extract all the files
zip_file.close() # close the zip file

In [4]:
# load the dataset 
import pandas as pd 

df = pd.read_csv('orders.csv')

In [5]:
# check the dataset
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [6]:
df.shape

(9994, 16)

In [7]:
#  unique values in the Ship Mode column 

df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [8]:
# had to replace the 'Not Available' and 'unknown' with NaN

df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])

In [9]:
# rename columns names... make them title_and replace spaces with underscores

df.columns = df.columns.str.title().str.replace(' ', '_')

In [10]:
df.columns

Index(['Order_Id', 'Order_Date', 'Ship_Mode', 'Segment', 'Country', 'City',
       'State', 'Postal_Code', 'Region', 'Category', 'Sub_Category',
       'Product_Id', 'Cost_Price', 'List_Price', 'Quantity',
       'Discount_Percent'],
      dtype='object')

In [11]:
# derive the new columns discount, List_price and Discount_percent 

df['Discount'] = df['List_Price'] * df['Discount_Percent'] * 0.01

In [12]:
# derive the new columns sale_price and profit

df['Sale_Price'] = df['List_Price'] - df['Discount']

df['Profit'] = df['Sale_Price'] - df['Cost_Price']

In [13]:
# dtypes pf dataset : 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_Id          9994 non-null   int64
 1   Order_Date        9994 non-null   object
 2   Ship_Mode         9988 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal_Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub_Category      9994 non-null   object
 11  Product_Id        9994 non-null   object
 12  Cost_Price        9994 non-null   int64
 13  List_Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount_Percent  9994 non-null   int64
 16  Discount          9994 non-null   float64
 17  Sale_Price        9994 non-null   float64
 18  Profit            9994 non-null   float64
dtypes: float64(3), int64(6), object(10)
memory usage: 1.4+ MB

In [17]:
# Convert the date from object dtype to datetime dtype.

df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%Y-%M-%D')

In [21]:
df.dtypes

Order_Id                     int64
Order_Date          datetime64[ns]
Ship_Mode                   object
Segment                     object
Country                     object
City                        object
State                       object
Postal_Code                  int64
Region                      object
Category                    object
Sub_Category                object
Product_Id                  object
Cost_Price                   int64
List_Price                   int64
Quantity                     int64
Discount_Percent             int64
Discount                   float64
Sale_Price                 float64
Profit                     float64
dtype: object

In [22]:
# drops columns -> cost price and list price and discount percent

df.drop(columns=['Cost_Price', 'List_Price', 'Discount_Percent'], inplace=True)

In [23]:
df.head()

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,Quantity,Discount,Sale_Price,Profit
0,1,2023-01-01 00:03:00,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-01-15 00:08:00,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10 00:01:00,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-01-18 00:06:00,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-01-13 00:07:00,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [24]:
# load the data into sql server using replace option

import pyodbc
import pymysql
from sqlalchemy import create_engine

engine = create_engine('mysql+pyodbc://@my_mysql_dsn')
con = engine.connect()

print("Data inserted")

Data inserted

In [ ]:
# load the data into sql server using append option

df.to_sql('orders_data', con=con, if_exists='append', index=False)